#!/bin/bash
# ad-fleet-install-hermes.sh — Install fleet Hermes on port 8001
# Part of: AcceleratingDigital Fleet (ad-fleet)
# Installs a SEPARATE, self-contained Hermes instance at ~/.ad-fleet/hermes/
# Independent from user's ~/.hermes/ on port 8000
# Minimal install: no browser, no computer-use, no bundled skills

set -euo pipefail

CONFIG="$HOME/.ad-fleet/config.yaml"
FLEET_HERMES_HOME="$HOME/.ad-fleet/hermes"
HERMES_INSTALL_DIR="$FLEET_HERMES_HOME/hermes-agent"
LOG="$HOME/.ad-fleet/logs/hermes-install.log"

mkdir -p "$HOME/.ad-fleet/logs" 2>/dev/null || true

log() { echo "$1"; echo "$(date): $1" >> "$LOG" 2>/dev/null || true; }
ok()   { echo "  ✅ $1"; echo "$(date): ✅ $1" >> "$LOG" 2>/dev/null || true; }
warn() { echo "  ⚠️  $1"; echo "$(date): ⚠️  $1" >> "$LOG" 2>/dev/null || true; }
fail() { echo "  ❌ $1"; echo "$(date): ❌ $1" >> "$LOG" 2>/dev/null || true; exit 1; }

# ─── Read fleet config ───────────────────────────────────────────────────────
LLM_URL=$(grep "llm_url:" "$CONFIG" | awk '{print $2}' | tr -d '"')
ROLE=$(grep "  role:" "$CONFIG" | awk '{print $2}' | tr -d '"')

# LiteLLM API key — stored in fleet config as llm_api_key
LLM_API_KEY=$(grep "llm_api_key:" "$CONFIG" | awk '{print $2}' | tr -d '"')
# Fallback: check if main Hermes .env has it
if [ -z "$LLM_API_KEY" ]; then
  LLM_API_KEY=$(grep "INFERENCE_CUSTOM_AD_LITELLM_API_KEY=" "$HOME/.hermes/.env" 2>/dev/null | cut -d'=' -f2)
fi
[ -z "$LLM_API_KEY" ] && fail "No LiteLLM API key found in fleet config or ~/.hermes/.env"

# Admins use internal LiteLLM, members use public domain
if [ "$ROLE" = "admin" ]; then
  PROVIDER_NAME="10.1.2.13:4000"
  BASE_URL="http://10.1.2.13:4000/v1"
else
  PROVIDER_NAME="llm.acceleratingdigital.com"
  BASE_URL="${LLM_URL}/v1"
fi

log "=== Fleet Hermes Installation (port 8001) ==="
log "Role: $ROLE | Provider: $PROVIDER_NAME | LLM: $BASE_URL"

# ─── Step 1: Check if already installed ──────────────────────────────────────
if [ -f "$HERMES_INSTALL_DIR/venv/bin/python" ] && [ -f "$FLEET_HERMES_HOME/config.yaml" ]; then
  ok "Hermes already installed"
else
  # ─── Step 2: Install Hermes (minimal, self-contained) ──────────────────────
  log "Step 1: Installing minimal Hermes to $FLEET_HERMES_HOME..."
  mkdir -p "$FLEET_HERMES_HOME"

  export HERMES_HOME="$FLEET_HERMES_HOME"
  export HERMES_INSTALL_DIR="$HERMES_INSTALL_DIR"

  curl -fsSL https://hermes-agent.nousresearch.com/install.sh | \
    HERMES_HOME="$FLEET_HERMES_HOME" \
    HERMES_INSTALL_DIR="$HERMES_INSTALL_DIR" \
    bash -s -- --skip-setup --skip-browser --skip-computer-use --no-skills 2>&1 | tail -5

  [ ! -f "$HERMES_INSTALL_DIR/venv/bin/python" ] && fail "Hermes installation failed"
  ok "Hermes installed (minimal: no browser, no computer-use, no skills)"
fi

# Ensure .no-bundled-skills flag is set
touch "$FLEET_HERMES_HOME/.no-bundled-skills"

# ─── Step 3: Write config.yaml ───────────────────────────────────────────────
log "Step 2: Writing fleet Hermes config..."

PYTHON_BIN="$HERMES_INSTALL_DIR/venv/bin/python"
VENV_DIR="$HERMES_INSTALL_DIR/venv"

# Generate API server key
API_SERVER_KEY=$("$PYTHON_BIN" -c "import secrets; print('ad-fleet-' + secrets.token_hex(16))" 2>/dev/null || echo "ad-fleet-$(date +%s)-default")

mkdir -p "$FLEET_HERMES_HOME/logs"

cat > "$FLEET_HERMES_HOME/config.yaml" << HERMESCFG
# Fleet Hermes Config — port 8001
# Auto-generated by ad-fleet installer
# SEPARATE from user's ~/.hermes/ on port 8000
# ad-fleet instance — do not mix with user Hermes

model:
  default: "algolia/xlarge"
  provider: "custom:${PROVIDER_NAME}"
  base_url: "${BASE_URL}"
  api_key: "${LLM_API_KEY}"
  context_length: 128000

custom_providers:
  - name: "${PROVIDER_NAME}"
    base_url: "${BASE_URL}"
    api_mode: "openai"
    api_key: "${LLM_API_KEY}"
    models:
      - "algolia/xlarge"
      - "algolia/medium"
      - "algolia/small"

agent:
  max_turns: 30

terminal:
  backend: local
  timeout: 120

display:
  interface: cli
  tool_progress: minimal

memory:
  memory_enabled: false
  user_profile_enabled: false

compression:
  enabled: true
  threshold: 0.5
  target_ratio: 0.2

approvals:
  mode: smart

platforms:
  api_server:
    enabled: true
    extra:
      port: 8001
      key: "${API_SERVER_KEY}"
HERMESCFG

ok "Config written"

# ─── Step 4: Write .env ──────────────────────────────────────────────────────
cat > "$FLEET_HERMES_HOME/.env" << ENVCFG
# Fleet Hermes environment — port 8001
# ad-fleet instance — separate from user's ~/.hermes/.env
INFERENCE_CUSTOM_AD_LITELLM_API_KEY=${LLM_API_KEY}
API_SERVER_PORT=8001
API_SERVER_KEY=${API_SERVER_KEY}
API_SERVER_HOST=127.0.0.1
ENVCFG
chmod 600 "$FLEET_HERMES_HOME/.env"
ok ".env written"

# ─── Step 5: Create LaunchAgent ──────────────────────────────────────────────
log "Step 3: Creating LaunchAgent..."

cat > ~/Library/LaunchAgents/com.ad-fleet.hermes-gateway.plist << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ad-fleet.hermes-gateway</string>

    <key>ProgramArguments</key>
    <array>
        <string>${PYTHON_BIN}</string>
        <string>-m</string>
        <string>hermes_cli.main</string>
        <string>gateway</string>
        <string>run</string>
        <string>--replace</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${FLEET_HERMES_HOME}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${VENV_DIR}/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>VIRTUAL_ENV</key>
        <string>${VENV_DIR}</string>
        <key>HERMES_HOME</key>
        <string>${FLEET_HERMES_HOME}</string>
        <key>INFERENCE_CUSTOM_AD_LITELLM_API_KEY</key>
        <string>${LLM_API_KEY}</string>
        <key>API_SERVER_PORT</key>
        <string>8001</string>
        <key>API_SERVER_KEY</key>
        <string>${API_SERVER_KEY}</string>
        <key>API_SERVER_HOST</key>
        <string>127.0.0.1</string>
        <key>HOME</key>
        <string>${HOME}</string>
    </dict>

    <key>LimitLoadToSessionType</key>
    <array>
        <string>Aqua</string>
        <string>Background</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${FLEET_HERMES_HOME}/logs/gateway.log</string>

    <key>StandardErrorPath</key>
    <string>${FLEET_HERMES_HOME}/logs/gateway.error.log</string>
</dict>
</plist>
PLIST

ok "LaunchAgent created (com.ad-fleet.hermes-gateway)"

# ─── Step 6: Load LaunchAgent ────────────────────────────────────────────────
log "Step 4: Starting fleet Hermes gateway..."

launchctl unload ~/Library/LaunchAgents/com.ad-fleet.hermes-gateway.plist 2>/dev/null || true
launchctl load ~/Library/LaunchAgents/com.ad-fleet.hermes-gateway.plist 2>/dev/null || true
sleep 8

# Verify
if launchctl list com.ad-fleet.hermes-gateway 2>/dev/null | grep -q "PID"; then
  PID=$(launchctl list com.ad-fleet.hermes-gateway 2>/dev/null | grep "PID" | awk '{print $2}' | tr -d ';')
  ok "Gateway running (PID: $PID)"
else
  warn "Gateway loaded but PID not confirmed — may still be starting"
fi

# ─── Step 7: Verify port 8001 ────────────────────────────────────────────────
log "Step 5: Verifying port 8001..."
sleep 3

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 http://127.0.0.1:8001/v1/models -H "Authorization: Bearer ${API_SERVER_KEY}" 2>/dev/null || echo "000")
if echo "$HTTP_CODE" | grep -q "200"; then
  ok "Port 8001 responding (HTTP 200)"
else
  warn "Port 8001 returned HTTP $HTTP_CODE — gateway may still be starting (10-30s)"
fi

# ─── Step 8: Verify LLM ──────────────────────────────────────────────────────
log "Step 6: Verifying LLM connectivity..."
LLM_TEST=$(curl -s --max-time 20 \
  http://127.0.0.1:8001/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${API_SERVER_KEY}" \
  -d '{"model":"hermes-agent","messages":[{"role":"user","content":"Say exactly: FLEET OK"}],"max_tokens":10,"stream":false}' \
  2>/dev/null | "$PYTHON_BIN" -c "import sys,json; r=json.loads(sys.stdin.read()); print(r.get('choices',[{}])[0].get('message',{}).get('content','ERROR'))" 2>/dev/null || echo "ERROR")

if echo "$LLM_TEST" | grep -q "FLEET OK"; then
  ok "LLM connectivity verified"
else
  warn "LLM test returned: $LLM_TEST"
fi

log ""
log "=== Fleet Hermes Installation Complete ==="
log "  HERMES_HOME: $FLEET_HERMES_HOME"
log "  Port: 8001"
log "  Model: algolia/xlarge via $BASE_URL"
log "  LaunchAgent: com.ad-fleet.hermes-gateway"
log "  Size: $(du -sh "$FLEET_HERMES_HOME" 2>/dev/null | awk '{print $1}')"
